### ISSUE TITLE
Consistency: add source (BRP) to credentials travelDocument and bsn

### ISSUE THREAD

**Issue by ehotting** [privacybydesign/pbdf-schememanager#3]
https://github.com/privacybydesign/pbdf-schememanager/blob/05896e8241701877543ea1552a2dee022f7b87aa/nijmegen/Issues/travelDocument/description.xml#L15
https://github.com/privacybydesign/pbdf-schememanager/blob/05896e8241701877543ea1552a2dee022f7b87aa/nijmegen/Issues/bsn/description.xml#L15

For credentials travelDocument and bsn, add information about source, being BRP. For consistency, as the other credentials contain this info in description.

**Comment by BramWithaar** [comment]
and technically: the issue implementation retrieves the BSN from BRP, and doesn't use the BSN provided by the DigiD authentication (it does use that bsn to retrieve the correct BRP record of course).

**Comment by timenolthof** [comment]
exactly

**Comment by ehotting** [comment]
Hmm, not sure. Thought experiment: If someone identifies with an authenticated BSN via DigiD, but we do not find the other attributes for that BSN in BRP, we cannot issue credentials. I'd say, the BSN from DigiD is just to identify the person, but we issue the BSN based on what we find in BRP. Would be interesting to do a more thorough analysis of this, conceptually, if not to decide on which description is the right one (which is not that important) - it's useful tot understand this fully I guess.

**Comment by timenolthof** [comment]
@ehotting you're saying exactly the same thing right?

**Comment by ehotting** [comment]
Reply was meant to be a reaction on [1st question](https://github.com/privacybydesign/pbdf-schememanager/issues/3#issuecomment-391263366). Had comment open for hours before submitting. We have three different ways to make the same claim indeed. Apologies for confusion!
