### ISSUE TITLE
Huisnummer

### ISSUE THREAD

**Issue by BramWithaar** [privacybydesign/pbdf-schememanager#4]
er komen potentieel 4 elementen terecht in dit veld, niet drie: nummer, letter, toevoeging, aanduiding.
De description is dus niet compleet.

**Comment by sietseringers** [comment]
Heb je een voorbeeld van zo'n aanduiding? En wat is de beste Engelse vertaling van 'aanduiding'?

**Comment by ehotting** [comment]
Context:
(Huisnummer)[http://www.stelselvanbasisregistraties.nl/begrippen/Adres/BRP/Woonadres_in_Nederland/Huisnummer-Woonadres_in_Nederland]
(Huisletter)[http://www.stelselvanbasisregistraties.nl/begrippen/Adres/BRP/Woonadres_in_Nederland/Huisletter-Woonadres_in_Nederland]
(Huisnummertoevoeging)[http://www.stelselvanbasisregistraties.nl/begrippen/Adres/BRP/Woonadres_in_Nederland/Huisnummertoevoeging-Woonadres_in_Nederland]

(Aanduiding bij huisnummer)[http://www.stelselvanbasisregistraties.nl/begrippen/Adres/BRP/Woonadres_in_Nederland/Aanduiding_bij_huisnummer-Woonadres_in_Nederland]

**Comment by timenolthof** [comment]
Persoonlijk vind ik ook het attributeId `number` iets te generiek. `houseNumber` is concreter. Is er in het standaardtaalgebruik ook een benaming voor het geheel van de 4 potentiële elementen? (bijvoorbeeld `huisaanduiding` ?

**Comment by ehotting** [comment]
Uitleg & voorbeeld aanduiding:

Er zijn verblijfsobjecten die geen echt eigen adres hebben, maar waarbij de locatie wordt afgeleid van een referentieadres. Wanneer in het veld "Aanduiding" iets opgenomen is, betekent het dat de andere gevulde velden niet het eigen adres beschrijven, maar het referentieadres.

Voorbeeld:
- Een woonboot ligt tegenover woning met adres Irmapad 3a

Het adres van de woonboot zou dan kunnen worden:  Irmapad 3a tegenover

Ik herinner mij (ben 20 jaar geleden GBA beheerder geweest) dat dit vaker voorkwam dan je zou verwachten, en zelfs adressen waarbij alle vier de velden gevuld zijn komen voor.

**Comment by ehotting** [comment]
"Aanduiding" is een semantisch onding wat je redelijk vaak tegenkomt in de basis- en kernregistraties, in allerlei contexten. Mooi vaag woord om vage dingen te koppelen aan een businessobject. Wat in deze context feitelijk bedoeld wordt is volgens mij een "referentieindicator / referenceIndicator", immers het verandert de betekenis van de andere adresvelden.

**Comment by sietseringers** [comment]
Dat helpt, dank! Met dat laatste ben ik het denk ik niet eens: ik kan me moeilijk voorstellen dat je wel het huisnummer, -letter en -toevoeging wil maar niet de aanduiding, of omgekeerd (enkel de aanduiding). Ook voor verifiers lijkt me dat onhandig: als de aanduiding in een apart attribuut staat en je vraagt daar niet om, dan kun je van wat je wel ontvangt niet zeker weten of het het huis van de attribuut-eigenaar aanwijst, of dat van een ander persoon.

Dus ik stel voor om er het volgende van te maken:

```xml
<Attribute id="houseNumber" optional="true">
	<Name>
		<en>House number</en>
		<nl>Huisnummer</nl>
	</Name>
	<Description>
		<en>Your house number, letter, addition and/or indication</en>
		<nl>Uw huisnummer, letter, toevoeging en/of aanduiding</nl>
	</Description>
</Attribute>
```
