### ISSUE TITLE
Cancelled because of outdated cards

### ISSUE THREAD

**Issue by rvanrosmalen** [privacybydesign/pbdf-schememanager#57]
Hi,

We are doing some try-outs with Irma. Requesting pbdf.nijmegen.bsn.bsn gives a cancel in the app because of outdated cards. How is this possible since the data for Nijmegen has not been updated for 6 months.

Kind regards,

Rob

**Comment by sietseringers** [comment]
Hi Rob,

The `pbdf.nijmegen` issuer and its cards have been deprecated, and all of the cards it has issued in the past should be expired by now.

The Nijmegen issuer now uses `pbdf.gemeente`, so if you ask for the [`pbdf.gemeente.personalData.bsn`](https://privacybydesign.foundation/attribute-index/en/pbdf.gemeente.personalData.html#pbdf.gemeente.personalData.bsn) attribute instead it should work.

**Comment by rvanrosmalen** [comment]
Thanks for the quick reply, this one works!
